In [1]:
import os
import pandas as pd
import numpy as np
from tifffile import imread
from tqdm import tqdm

import sys
from pathlib import Path
from mlxtend.evaluate import mcnemar_table
from mlxtend.evaluate import mcnemar

cwd = os.getcwd()
# print(f"Working dir: {cwd}")
module_path = os.path.abspath(Path(cwd).parents[3])
# print(f"Module dir: {module_path}")
if module_path not in sys.path:
    sys.path.append(module_path)

import seaborn as sns
sns.set_theme(style="darkgrid")
sns.set_palette("Set2")

In [3]:
df_4 = pd.read_csv(os.path.join(module_path, "experiments", "exp12-4", "results-defaults", "288x288", "reg_props" ,"all.csv"))

In [4]:
df_4 = df_4.set_index("label", drop=False)
df_4n = df_4[["label", "actual_frame","IoU"]]
clm=["lbl", "actual_frame","IoU"]
df_4n.columns=clm
df_4n

lbl  actual_frame       IoU
label                             
1        1             8  0.827494
2        2             8  0.807711
3        3             8  0.869768
4        4             8  0.876451
1        1            24  0.830142
...    ...           ...       ...
25      25           344  0.768193
26      26           344  0.801151
27      27           344  0.631261
28      28           344  0.727184
29      29           344  0.000000

[416 rows x 3 columns]

In [5]:
df_11 = pd.read_csv(os.path.join(module_path, "experiments", "exp11", "results_defaults", "reg_props", "all.csv"))

In [6]:
df_11 = df_11.set_index("label", drop=False)
df_11n = df_11[["label", "actual_frame","IoU"]]
clm=["lbl", "actual_frame","IoU"]
df_11n.columns=clm
df_11n

lbl  actual_frame       IoU
label                             
1        1             8  0.816612
2        2             8  0.829453
3        3             8  0.870603
4        4             8  0.866384
1        1            24  0.825465
...    ...           ...       ...
27      27           344  0.707868
28      28           344  0.662815
29      29           344  0.000000
30      30           344  0.000000
31      31           344  0.000000

[435 rows x 3 columns]

In [7]:
result=pd.merge(df_11n,df_4n,how="left", on=["lbl", "actual_frame"], indicator=True)
#result=df_4n.compare(df_11n)
pd.set_option('display.max_rows', result.shape[0]+1)
result

lbl  actual_frame     IoU_x     IoU_y     _merge
0      1             8  0.816612  0.827494       both
1      2             8  0.829453  0.807711       both
2      3             8  0.870603  0.869768       both
3      4             8  0.866384  0.876451       both
4      1            24  0.825465  0.830142       both
5      2            24  0.836237  0.851157       both
6      3            24  0.852276  0.863057       both
7      4            24  0.901500  0.902856       both
8      1            31  0.840030  0.839191       both
9      2            31  0.831209  0.838863       both
10     3            31  0.862278  0.875595       both
11     4            31  0.903380  0.906850       both
12     1            51  0.834766  0.853614       both
13     2            51  0.839324  0.844347       both
14     3            51  0.854639  0.849221       both
15     4            51  0.884084  0.900443       both
16     1            58  0.860456  0.882531       both
17     2            58  0.836307  0.854237       both
18     3            58  0.831851  0.839460       both
19     4            58  0.873864  0.909468       both
20     1            62  0.842228  0.856163       both
21     2            62  0.853150  0.842957       both
22     3            62  0.820755  0.829377       both
23     4            62  0.895768  0.910430       both
24     1            66  0.840713  0.840043       both
25     2            66  0.822924  0.813983       both
26     3            66  0.829924  0.816769       both
27     4            66  0.895804  0.856246       both
28     1            67  0.823902  0.841073       both
29     2            67  0.831000  0.823974       both
30     3            67  0.836797  0.834804       both
31     4            67  0.886608  0.872769       both
32     1            73  0.867067  0.861334       both
33     2            73  0.824680  0.839293       both
34     3            73  0.803015  0.812161       both
35     4            73  0.862187  0.880992       both
36     1            81  0.834587  0.846188       both
37     2            81  0.849328  0.831306       both
38     3            81  0.783769  0.802537       both
39     4            81  0.837478  0.823236       both
40     5            81  0.843810  0.848134       both
41     6            81  0.809761  0.816831       both
42     1            91  0.851175  0.852265       both
43     2            91  0.836808  0.833252       both
44     3            91  0.844258  0.859915       both
45     4            91  0.861248  0.895094       both
46     5            91  0.791656  0.787081       both
47     6            91  0.816055  0.816741       both
48     1           106  0.842116  0.864427       both
49     2           106  0.826580  0.789489       both
50     3           106  0.834876  0.830384       both
51     4           106  0.764227  0.723317       both
52     5           106  0.847682  0.842994       both
53     6           106  0.826872  0.841141       both
54     7           106  0.831369  0.860741       both
55     8           106  0.831912  0.845761       both
56     1           128  0.858817  0.862107       both
57     2           128  0.848437  0.872708       both
58     3           128  0.811268  0.808765       both
59     4           128  0.868768  0.841982       both
60     5           128  0.834073  0.856389       both
61     6           128  0.841005  0.851925       both
62     7           128  0.828378  0.827790       both
63     8           128  0.864254  0.852006       both
64     1           148  0.848597  0.880120       both
65     2           148  0.849325  0.850298       both
66     3           148  0.838895  0.830144       both
67     4           148  0.868674  0.855067       both
68     5           148  0.845056  0.821135       both
69     6           148  0.849935  0.882141       both
70     7           148  0.842081  0.850913       both
71     8           148  0.872565  0.863121       both
72     9           148  0.000000       NaN  left_only
73     1 

In [8]:
arr_4= np.where(result["IoU_y"].isna(), 0, 1)
arr_4

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [9]:
arr_11= np.where(result["IoU_x"].isna(), 0, 1)
arr_11

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [10]:
arr_gt = np.where(result["IoU_x"]>0.3, 1, 0)
arr_gt

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,

In [11]:
tb = mcnemar_table(y_target=arr_gt, 
                   y_model1=arr_4, 
                   y_model2=arr_11)
tb

array([[362,  20],
       [  0,  53]])

In [12]:
chi2, p = mcnemar(ary=tb, corrected=True)
print('chi-squared:', chi2)
print(f'p-value: {p:.8f}')

chi-squared: 18.05
p-value: 0.00002152


In [13]:
chi2, p = mcnemar(ary=tb, corrected=False)
print('chi-squared:', chi2)
print(f'p-value: {p:.8f}')

chi-squared: 20.0
p-value: 0.00000774


In [14]:
# interpret the p-value
alpha = 0.05
if p > alpha:
	print('Same proportions of errors (fail to reject H0)')
else:
	print('Different proportions of errors (reject H0)')

Different proportions of errors (reject H0)
